// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOB9B_5qpc6XxwHi_4KHti33dHSJCn6e4',
    appId: '1:36150152415:web:0cd2aac91f4b08a188ad6a',
    messagingSenderId: '36150152415',
    projectId: 'test-bb802',
    authDomain: 'test-bb802.firebaseapp.com',
    storageBucket: 'test-bb802.firebasestorage.app',
    measurementId: 'G-GJP4X32NBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXtMAYH9Pno9MxzF0yi_MlJN7KDINfw0',
    appId: '1:36150152415:android:8ce743ea87b9a69588ad6a',
    messagingSenderId: '36150152415',
    projectId: 'test-bb802',
    storageBucket: 'test-bb802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOM-kHOJQ8rIQMsaaHAfhAixAznXqR0HY',
    appId: '1:36150152415:ios:c414bf2eef251ce188ad6a',
    messagingSenderId: '36150152415',
    projectId: 'test-bb802',
    storageBucket: 'test-bb802.firebasestorage.app',
    iosBundleId: 'com.example.eCoomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOM-kHOJQ8rIQMsaaHAfhAixAznXqR0HY',
    appId: '1:36150152415:ios:c414bf2eef251ce188ad6a',
    messagingSenderId: '36150152415',
    projectId: 'test-bb802',
    storageBucket: 'test-bb802.firebasestorage.app',
    iosBundleId: 'com.example.eCoomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOB9B_5qpc6XxwHi_4KHti33dHSJCn6e4',
    appId: '1:36150152415:web:01d9da24b3c0b54888ad6a',
    messagingSenderId: '36150152415',
    projectId: 'test-bb802',
    authDomain: 'test-bb802.firebaseapp.com',
    storageBucket: 'test-bb802.firebasestorage.app',
    measurementId: 'G-RV8N21WQ1L',
  );

}